<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>


  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="9.0.8" />
    <PackageReference Include="Microsoft.FluentUI.AspNetCore.Components.Icons" Version="4.12.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Libraries\ApiContracts\HT.Api.Service.Contracts\HT.Api.Service.Contracts.csproj" />
    <ProjectReference Include="..\..\..\Libraries\Configuration\HT.Microsoft.IConfiguration.Extensions\HT.Microsoft.IConfiguration.Extensions.csproj" />
    <ProjectReference Include="..\..\..\Libraries\Logging\HT.Microsoft.ILogger.Extensions\HT.Microsoft.ILogger.Extensions.csproj" />
    <ProjectReference Include="..\..\..\Libraries\SqlClient\HT.Microsoft.SqlClient.Extensions\HT.Microsoft.SqlClient.Extensions.csproj" />
    <ProjectReference Include="..\ResourceMapper.Common.Shared\ResourceMapper.Common.Shared.csproj" />
  </ItemGroup>

</Project>
