<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
    <DebugType>portable</DebugType>
    <DebugSymbols>true</DebugSymbols>
  </PropertyGroup>

  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="9.0.8" />
    <PackageReference Include="Microsoft.FluentUI.AspNetCore.Components" Version="4.12.1" />
    <PackageReference Include="Microsoft.FluentUI.AspNetCore.Components.Icons" Version="4.12.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Libraries\ApiContracts\HT.ApiContracts\HT.Api.Client.Contracts.csproj" />
    <ProjectReference Include="..\ResourceMapper.Common.Shared\ResourceMapper.Common.Shared.csproj" />
  </ItemGroup>

</Project>
