using System.Text.RegularExpressions;
using HT.Api.Service.Contracts.BuildersOfT;

namespace ResourceMapper.Common.Server.SavedViews
{
    /// <summary>
    /// Input rules for saved views, in one place so the service and any other caller cannot drift.
    /// <para>
    /// Nothing here defends against SQL injection — every database call goes through a stored
    /// procedure with typed parameters (<c>AddVarchar</c> / <c>AddNVarchar</c> / <c>AddTvp</c>) and
    /// no SQL text is ever concatenated. These rules exist so that bad input is refused with a
    /// clear message instead of being truncated by a column, corrupting a URL, or arriving as an
    /// unbounded payload.
    /// </para>
    /// </summary>
    public static class SavedViewValidation
    {
        public const int MaxOwnerIdLength = 64;      // VARCHAR(64)
        public const int MaxNameLength = 200;        // NVARCHAR(200)
        public const int MaxUidLength = 40;          // VARCHAR(40)

        /// <summary>
        /// QueryString is NVARCHAR(MAX) so the database imposes no limit, but an API endpoint with
        /// no limit is an invitation to store megabytes. Four filters over the catalog's
        /// highest-cardinality tags come to roughly 2100 characters, so 8000 is generous headroom
        /// while still being a limit.
        /// </summary>
        public const int MaxQueryStringLength = 8000;

        /// <summary>Uids are generated by this service; anything else is a caller error.</summary>
        private static readonly Regex UidPattern = new(@"^[A-Za-z0-9_-]+$", RegexOptions.Compiled);

        /// <summary>
        /// A saved query is replayed by appending it to a path and handing it to the navigation
        /// manager. Anything that is not a plain query string could redirect somewhere else, so the
        /// shape is checked rather than trusted.
        /// </summary>
        private static readonly Regex QueryStringPattern = new(@"^\?[^\s#]*$", RegexOptions.Compiled);

        public static void ValidateOwnerId<T>(ServiceResponseBuilder<T> builder, string ownerId)
            where T : class, new()
        {
            if (string.IsNullOrWhiteSpace(ownerId))
                builder.Validation.AddValidation("ownerId", "Is required");
            else if (ownerId.Length > MaxOwnerIdLength)
                builder.Validation.AddValidation("ownerId", $"Must be {MaxOwnerIdLength} characters or fewer");
        }

        /// <summary>Returns the trimmed name; adds validations when it is unusable.</summary>
        public static string ValidateName<T>(ServiceResponseBuilder<T> builder, string? name)
            where T : class, new()
        {
            var trimmed = (name ?? string.Empty).Trim();

            if (string.IsNullOrWhiteSpace(trimmed))
                builder.Validation.AddValidation("name", "Is required");
            else if (trimmed.Length > MaxNameLength)
                builder.Validation.AddValidation("name", $"Must be {MaxNameLength} characters or fewer");
            else if (ContainsControlCharacters(trimmed))
                builder.Validation.AddValidation("name",
                    "Must not contain line breaks or control characters");

            return trimmed;
        }

        public static void ValidateQueryString<T>(ServiceResponseBuilder<T> builder, string? queryString)
            where T : class, new()
        {
            if (string.IsNullOrWhiteSpace(queryString))
            {
                builder.Validation.AddValidation("queryString", "Is required");
                return;
            }

            if (queryString.Length > MaxQueryStringLength)
            {
                builder.Validation.AddValidation("queryString",
                    $"Must be {MaxQueryStringLength} characters or fewer");
                return;
            }

            if (!QueryStringPattern.IsMatch(queryString))
                builder.Validation.AddValidation("queryString",
                    "Must be a query string beginning with '?' and containing no whitespace or fragment");
        }

        /// <summary>Optional on save (empty means create); required for delete and set-default.</summary>
        public static void ValidateUid<T>(ServiceResponseBuilder<T> builder, string? uid, bool required)
            where T : class, new()
        {
            if (string.IsNullOrWhiteSpace(uid))
            {
                if (required) builder.Validation.AddValidation("savedViewUid", "Is required");
                return;
            }

            if (uid.Length > MaxUidLength)
                builder.Validation.AddValidation("savedViewUid", $"Must be {MaxUidLength} characters or fewer");
            else if (!UidPattern.IsMatch(uid))
                builder.Validation.AddValidation("savedViewUid",
                    "Must contain only letters, digits, hyphens and underscores");
        }

        private static bool ContainsControlCharacters(string value)
        {
            foreach (var c in value)
                if (char.IsControl(c)) return true;
            return false;
        }
    }
}
