---- NOTE: Enable COMMIT below
--USE [HT.Services]
--GO
--DROP PROC IF EXISTS #SeedTagType
--DROP PROC IF EXISTS #SeedResource
--DROP PROC IF EXISTS #SeedTagDefinition
--DROP PROC IF EXISTS #AssignTagDefToResourceType
--DROP PROC IF EXISTS #Seed_Resource
--DROP PROC IF EXISTS #AssignTagToResource
--DROP PROC IF EXISTS #ResourceDependsOn
--DROP PROC IF EXISTS #SeedResourceType
--DROP PROC IF EXISTS #Add_Tag_ToResource
--GO

--CREATE PROC #SeedTagType(
--    @TagTypeId INT
--    ,@TagCode VARCHAR(50)
--)
--AS
--BEGIN
--    UPDATE TOP(1)
--        [HTResourceMapper].TagContentType
--    SET
--        TagCode = @TagCode
--    WHERE
--        TagContentTypeId = @TagTypeId
--    IF @@ROWCOUNT = 0
--    BEGIN
--        INSERT INTO [HTResourceMapper].TagContentType (
--            TagContentTypeId,
--            TagCode
--        ) VALUES (
--            @TagTypeId
--            ,@TagCode
--        )
--    END
--END
--GO
--CREATE PROC #SeedResourceType (
--    @TypeName NVARCHAR(250)
--    ,@AllowCustomTags BIT = 1
--) AS
--BEGIN
--    DECLARE @ResourceTypeId INT
--    SELECT TOP(1) @ResourceTypeId=ResourceTypeId FROM [HTResourceMapper].ResourceType WHERE TypeName = @TypeName
--    IF @ResourceTypeId IS NULL
--    BEGIN
--        INSERT INTO [HTResourceMapper].[ResourceType] (
--            AllowCustomTags
--            , ResourceTypeUid
--            , TypeName
--            , CreatedOn

--        ) VALUES (
--            @AllowCustomTags
--            , 'RT'+LOWER(REPLACE(CAST(NEWID() AS VARCHAR(40)),'-',''))
--            , @TypeName
--            , SYSUTCDATETIME()
--        )
--        RETURN
--    END
--    UPDATE TOP(1)
--        [HTResourceMapper].[ResourceType]
--    SET
--        AllowCustomTags = @AllowCustomTags
--        , UpdatedOn = SYSUTCDATETIME()
--    WHERE
--        [ResourceTypeId] = @ResourceTypeId
--END
--GO
--CREATE PROC #SeedTagDefinition(
--    @TagKey NVARCHAR(50)
--    , @ValueContentType VARCHAR(50)
--    , @AllowCustomValues BIT = 1
--    , @IsMultiValued BIT = 0
--    , @AllowedValues NVARCHAR(2000)
--    , @IsSystemTag BIT = 0
--) AS
--BEGIN
--    DECLARE @TagDefinitonId INT, @ContentTypeId INT
--    SELECT TOP(1) @TagDefinitonId = TagDefinitionId FROM [HTResourceMapper].[TagDefinition] WHERE TagDefinitionKey = @TagKey
--	SELECT TOP(1) @ContentTypeId = TagContentTypeId FROM [HTResourceMapper].[TagContentType] WHERE TagCode = @ValueContentType
--    IF @TagDefinitonId IS NULL
--    BEGIN
--       INSERT INTO [HTResourceMapper].[TagDefinition] (
--            TagDefinitionUid
--            , TagDefinitionKey
--            , TagContentTypeId
--            , AllowCustomValue

--            , IsMultiValued
--            , AllowedValues
--            , IsSystemTag
--            , CreatedOn

--       ) VALUES (
--            'TD'+LOWER(REPLACE(CAST(NEWID() AS VARCHAR(40)),'-',''))
--            , @TagKey
--            , @ContentTypeId
--            , @AllowCustomValues

--            , @IsMultiValued
--            , @AllowedValues
--            , @IsSystemTag
--            , SYSUTCDATETIME()
--       )
--       RETURN
--    END
--    UPDATE TOP(1)
--        [HTResourceMapper].[TagDefinition]
--    SET
--        TagContentTypeId = @ContentTypeId
--        , AllowCustomValue = @AllowCustomValues
--        , IsMultiValued = @IsMultiValued
--        , AllowedValues = @AllowedValues
        
--        , IsSystemTag = @IsSystemTag
--        , UpdatedOn = SYSUTCDATETIME()        
--    WHERE 
--        TagDefinitionId = @TagDefinitonId
--END
--GO
--CREATE PROC #AssignTagDefToResourceType (
--    @ResourceTypeKey NVARCHAR(250)
--    , @TagKey NVARCHAR(50)
--    , @IsTagRequired BIT = 0
--) AS
--BEGIN
--    DECLARE @ResourceTypeId INT, @TagId INT, @ResourceTypeTagId INT
--    SELECT TOP(1) @ResourceTypeId = ResourceTypeId FROM [HTResourceMapper].[ResourceType] WHERE TypeName = @ResourceTypeKey
--    SELECT TOP(1) @TagId = TagDefinitionId FROM [HTResourceMapper].[TagDefinition] WHERE TagDefinitionKey = @TagKey

--    IF @ResourceTypeId IS NULL OR @TagId IS NULL
--    BEGIN
--        RETURN
--    END
--    SELECT TOP(1) @ResourceTypeTagId = ResourceTypeTagId FROM [HTResourceMapper].[ResourceTypeTag] WHERE
--        ResourceTypeId = @ResourceTypeId AND TagDefintionId = @TagId
--    IF @ResourceTypeTagId IS NULL
--    BEGIN
--        INSERT INTO [HTResourceMapper].[ResourceTypeTag] (

--            TagDefintionId
--			,ResourceTypeId
--            ,IsTagRequired
--        ) VALUES (
--            @TagId
--			,@ResourceTypeId
--            ,@IsTagRequired
--        )
--    END
--    UPDATE TOP(1)
--        [HTResourceMapper].[ResourceTypeTag]
--    SET
--        IsTagRequired = @IsTagRequired
--    WHERE
--        ResourceTypeTagId = @ResourceTypeTagId    
--END
--GO
--CREATE PROC #Seed_Resource (
--    @ResourceKey NVARCHAR(250)
--    ,@ResourceName NVARCHAR(250)
--    ,@ResourceTypeKey NVARCHAR(250)= NULL
--    ,@Description NVARCHAR(2000) = NULL
--) AS
--BEGIN
--    DECLARE @ResourceId INT,@ResourceTypeId INT
--    SELECT TOP(1) @ResourceId = ResourceId FROM [HTResourceMapper].[Resource] WHERE ResourceKey = @ResourceKey
--    SELECT TOP(1) @ResourceTypeId=ResourceTypeId FROM [HTResourceMapper].[ResourceType] WHERE TypeName = @ResourceTypeKey

--    IF @ResourceId IS NULL 
--    BEGIN
--        INSERT INTO [HTResourceMapper].[Resource] (
--            ResourceUid
--            ,ResourceKey
--            ,ResourceName
--            ,[Description]

--            ,CreatedOn
--            ,ResourceTypeId
--        ) VALUES (
--            'RSC'+LOWER(REPLACE(CAST(NEWID() AS VARCHAR(40)),'-','')) 
--            ,coalesce(@ResourceKey,@ResourceName)
--            ,coalesce(@ResourceName,@ResourceKey)
--            ,@Description

--            ,SYSUTCDATETIME()
--            ,@ResourceTypeId
--        )
--        RETURN
--    END
--    UPDATE TOP(1)
--        [HTResourceMapper].[Resource]
--    SET
--        ResourceName = COALESCE(@ResourceName,@ResourceKey)
--        ,[Description] = @Description
--        ,UpdatedOn = SYSUTCDATETIME()
--    WHERE
--        ResourceId = @ResourceId
--END
--GO
--CREATE PROC #AssignTagToResource(
--    @ResourceKey NVARCHAR(250)
--    ,@TagKey NVARCHAR(50)
--    ,@TagValue NVARCHAR(2000)
--) AS
--BEGIN
--    DECLARE @ResourceId INT, @TagId INT, @ResourceTagId INT
--    SELECT TOP(1) @ResourceId = ResourceId FROM [HTResourceMapper].[Resource] WHERE ResourceKey = @ResourceKey
--    SELECT TOP(1) @TagId = TagDefinitionId FROM [HTResourceMapper].[TagDefinition] WHERE TagDefinitionKey = @TagKey
--    IF @ResourceId IS NULL OR @TagId IS NULL
--    BEGIN        
--        RETURN
--    END
--    SELECT TOP(1) @ResourceTagId FROM [HTResourceMapper].[ResourceTag] WHERE
--        TagDefinitionId = @TagId AND ResourceId = @ResourceId

--    IF @ResourceTagId IS NULL
--    BEGIN
--        INSERT INTO [HTResourceMapper].[ResourceTag] (
--            ResourceId
--            , TagDefinitionId
--            , TagValue
--            , CreatedOn
--        ) VALUES (
--            @ResourceId
--            , @TagId
--            , @TagValue
--            , SYSUTCDATETIME()
--        )
--        RETURN
--    END

--    UPDATE TOP(1)
--        [HTResourceMapper].[ResourceTag]
--    SET
--        TagValue = @TagValue

--        , UpdatedOn = SYSUTCDATETIME()
    
--END
--GO
--CREATE PROC #ResourceDependsOn(
--    @ResourceKey NVARCHAR(250)
--    ,@DependsOnKey NVARCHAR(250)
--) AS
--BEGIN
--    DECLARE @ResourceId INT, @DependencyResourceId INT, @DependencyId INT
--    SELECT TOP(1) @ResourceId = ResourceId FROM [HTResourceMapper].[Resource] WHERE [ResourceKey] = @ResourceKey 
--    SELECT TOP(1) @DependencyResourceId = ResourceId FROM [HTResourceMapper].[Resource] WHERE [ResourceKey] = @DependsOnKey
--    IF @ResourceId IS NULL OR @DependencyResourceId IS NULL
--    BEGIN
--	SELECT
--		'NULL FOUND'
--	RETURN
--    END
--    SELECT TOP(1) @DependencyId = [ResourceDependencyId] FROM [HTResourceMapper].[ResourceDependency] WHERE
--        ResourceId = @ResourceId AND DependencyResourceId = @DependencyResourceId
--    IF @DependencyId IS NULL
--    BEGIN
--        INSERT INTO [HTResourceMapper].[ResourceDependency] (
--            ResourceId
--            ,DependencyResourceId
--            ,CreatedOn
--        ) VALUES (
--            @ResourceId
--            ,@DependencyResourceId
--            ,SYSUTCDATETIME()
--        )
--    END
--END

--GO
--CREATE PROC #Add_Tag_ToResource(
--	@ResourceKey NVARCHAR(250)
--	,@TagKey NVARCHAR(50)
--	,@TagValue NVARCHAR(2000)
--) AS
--BEGIN
--	DECLARE @TagDefinitionId INT, @ResourceTagId INT,@IsMultiValued BIT=0,@ResourceId INT
--	SELECT TOP(1) @ResourceId = ResourceId from [HTResourceMapper].[Resource] WHERE ResourceKey = @ResourceKey
--	IF @ResourceId IS NULL
--	BEGIN
--		RETURN
--	END
--	SELECT TOP(1) @TagDefinitionId = TagDefinitionId,@IsMultiValued=IsMultiValued FROM [HTResourceMapper].TagDefinition WHERE TagDefinitionKey = @TagKey

--	IF @TagDefinitionId IS NULL -- CREATE TAG DEFINTION IF IT DOESN'T ALREADY EXIST
--	BEGIN
--		DECLARE @TagValueTypeId INT
--		IF CHARINDEX('://',@TagValue) > 0
--		BEGIN
--			SELECT top(1) @TagValueTypeId = TagContentTypeId FROM [HTResourceMapper].[TagContentType] WHERE TagCode = 'Link'
--		END
--		ELSE
--		BEGIN
--			SELECT top(1) @TagValueTypeId = TagContentTypeId FROM [HTResourceMapper].[TagContentType] WHERE TagCode = 'Text'						
--		END
		
--		INSERT INTO [HTResourceMapper].[TagDefinition] (
--			TagDefinitionUid
--			,TagDefinitionKey
--			,TagContentTypeId
--			,AllowCustomValue

--			,IsMultiValued
--			,AllowedValues
--			,IsSystemTag
--			,CreatedOn
--		) VALUEs (
--			'TD'+LOWER(REPLACE(CAST(NEWID() AS VARCHAR(40)),'-',''))
--			, @TagKey
--			, @TagValueTypeId
--			, 1

--			, 1
--			, NULL
--			, 0
--			,SYSDATETIME()
--		)
--		SET @TagDefinitionId = @@IDENTITY 
--		SET @IsMultiValued = 0
--	END

--	-- tag definition now exists in the db

--	SELECT TOP(1)
--		@TagDefinitionId = TagDefinitionId
--		,@IsMultiValued = IsMultiValued
--	FROM
--		[HTResourceMapper].[TagDefinition]
--	WHERE
--		TagDefinitionKey = @TagKey

--	SELECT TOP(1)
--		@ResourceTagId = ResourceTagId
--	FROM
--		[HTResourceMapper].[ResourceTag]
--	WHERE
--		ResourceId = @ResourceId
--	AND
--		TagDefinitionId = @TagDefinitionId

	
--	IF @ResourceTagId IS NULL
--	BEGIN
--	--   select 'inserting into resource tag',@tagkey,@tagvalue,@TagDefinitionId 'TAG DEFINTION ID', @IsMultiValued 'MULTI-VALUE', @ResourceTagId 'EXISTING RESOURCE TAG ID'
--		INSERT INTO [HTResourceMapper].[ResourceTag] (
--			ResourceId
--			,TagDefinitionId
--			,TagValue
--			,CreatedOn
--		) VALUES (
--			@ResourceId
--			,@TagDefinitionId
--			,@TagValue
--			,SYSUTCDATETIME()
--		)
--		RETURN
--	END

--	-- IF NOT MULTI-VALUED ATTEMPT TO UPDATE
--	IF @IsMultiValued = 0
--	BEGIN
--	--select 'updating singleton key',@Tagkey,@tagvalue,@TagDefinitionId 'TAG DEFINTION ID', @IsMultiValued 'MULTI-VALUE', @ResourceTagId 'EXISTING RESOURCE TAG ID',@ResourceId 'resource id'
--		UPDATE
--			[HTResourceMapper].[ResourceTag]
--		SET
--			TagValue = @TagValue
--		WHERE
--			ResourceTagId = @ResourceTagId
--		RETURN
	
--	END
	
--	-- IF MULTI VALUED AND VALUE IS DIFFERENT THEN INSERT
	
--	IF NOT EXISTS (
--		SELECT 
--			1
--		FROM
--			[HTResourceMapper].[ResourceTag]
--		WHERE
--			TagDefinitionId = @TagDefinitionId
--		AND
--			TagValue = @TagValue
--	) BEGIN
--	--	selecT 'adding multi-value key',@Tagkey,@tagvalue,@TagDefinitionId 'TAG DEFINTION ID', @IsMultiValued 'MULTI-VALUE', @ResourceTagId 'EXISTING RESOURCE TAG ID',@ResourceId 'resource id'		
--		INSERT INTO [HTResourceMapper].[ResourceTag] (
--			ResourceId
--			,TagDefinitionId
--			,TagValue
--			,CreatedOn
--		) VALUES (
--			@ResourceId
--			,@TagDefinitionId
--			,@TagValue
--			,SYSUTCDATETIME()
--		)
--	END
--END
--GO
--BEGIN TRANSACTION
--/*
--DELETE [HTResourceMapper].[ResourceDependency]
--DELETE [HTResourceMapper].[ResourceTag]
--DELETE [HTResourceMapper].[Resource]
--DELETE [HTResourceMapper].[ResourceTypeTag]
--DELETE [HTResourceMapper].[TagDefinition]
--DELETE [HTResourceMapper].[TagContentType]
--*/
--EXEC #SeedTagType @TagTypeId=0, @TagCode='Text'
--EXEC #SeedTagType @TagTypeId=1, @TagCode='Link'

--EXEC #SeedTagDefinition @TagKey = N'Azure Link', @ValueContentType='Link',@AllowCustomValues=1, @IsMultiValued=0, @AllowedValues=NULL, @IsSystemTag=0
--EXEC #SeedTagDefinition @TagKey = N'MP Environment', @ValueContentType='Text',@AllowCustomValues=0, @IsMultiValued=1, @AllowedValues=N'production, preview, preprod, integrationtest, development, localhost, shared-prod, shared-non-prod, all', @IsSystemTag=0

--EXEC #SeedResourceType @TypeName = N'Product', @AllowCustomTags = 1
--EXEC #SeedResourceType @TypeName = N'App Service', @AllowCustomTags = 1
--EXEC #SeedResourceType @TypeName = N'Database Server', @AllowCustomTags = 1
--EXEC #SeedResourceType @TypeName = N'Database', @AllowCustomTags = 1
--EXEC #SeedResourceType @TypeName = N'SF Cluster', @AllowCustomTags = 1
--EXEC #SeedResourceType @TypeName = N'App Insights', @AllowCustomTags = 1
--EXEC #SeedResourceType @TypeName = N'Gateway', @AllowCustomTags = 1
--EXEC #SeedResourceType @TypeName = N'Service Bus', @AllowCustomTags = 1
--EXEC #SeedResourceType @TypeName = N'Service Bus Queue', @AllowCustomTags = 1
--EXEC #SeedResourceType @TypeName = N'Repo', @AllowCustomTags = 1
--EXEC #SeedResourceType @TypeName = N'Build Pipeline', @AllowCustomTags = 1
--EXEC #SeedResourceType @TypeName = N'Redis Cache', @AllowCustomTags = 1
--EXEC #SeedResourceType @TypeName = N'SQL Managed Instance', @AllowCustomTags = 1
--EXEC #SeedResourceType @TypeName = N'External Service', @AllowCustomTags = 1

--EXEC #Seed_Resource @ResourceKey='dev-visibility-api',@ResourceName = 'vNext (API)',@ResourceTypeKey='App Service',@Description='Single ui/api for vNext (dev)'
--EXEC #Add_Tag_ToResource @ResourceKey = 'dev-visibility-api', @TagKey='Resource Link',@TagValue=N'https://portal.azure.com/#@descartessystems.onmicrosoft.com/resource/subscriptions/1d6dcbc4-27e3-4f74-a34d-89a09505ccd3/resourceGroups/usspi-rsg-dt-mplt-92/providers/Microsoft.Web/sites/dev-visibility-api/appServices'
--EXEC #Add_Tag_ToResource @ResourceKey = 'dev-visibility-api', @TagKey='Host Link',@TagValue=N'https://portal.azure.com/#@descartessystems.onmicrosoft.com/resource/subscriptions/1d6dcbc4-27e3-4f74-a34d-89a09505ccd3/resourceGroups/usspi-rsg-dt-mplt-92/providers/Microsoft.Web/sites/dev-visibility-api/appServices'
--EXEC #Add_Tag_ToResource @ResourceKey = 'dev-visibility-api', @TagKey='MP Environment',@TagValue=N'develop'
--EXEC #Add_Tag_ToResource @ResourceKey = 'dev-visibility-api', @TagKey='Resource Group',@TagValue=N'non-prod'
--EXEC #Add_Tag_ToResource @ResourceKey = 'dev-visibility-api', @TagKey='Product',@TagValue=N'vNext'

--EXEC #Seed_Resource @ResourceKey='dev-access-api',@ResourceName = 'Access Control Service',@ResourceTypeKey='App Service',@Description='Service for MDLP password validation and CAP,VIS SSO'
--EXEC #Add_Tag_ToResource @ResourceKey = 'dev-access-api', @TagKey='Resource Link',@TagValue=N'https://portal.azure.com/#@descartessystems.onmicrosoft.com/resource/subscriptions/1d6dcbc4-27e3-4f74-a34d-89a09505ccd3/resourceGroups/usspi-rsg-dt-mplt-92/providers/Microsoft.Web/sites/dev-visibility-api/appServices'
--EXEC #Add_Tag_ToResource @ResourceKey = 'dev-access-api', @TagKey='Host Link',@TagValue=N'https://portal.azure.com/#@descartessystems.onmicrosoft.com/resource/subscriptions/1d6dcbc4-27e3-4f74-a34d-89a09505ccd3/resourceGroups/usspi-rsg-dt-mplt-92/providers/Microsoft.Web/sites/dev-visibility-api/appServices'
--EXEC #Add_Tag_ToResource @ResourceKey = 'dev-access-api', @TagKey='MP Environment',@TagValue=N'develop'
--EXEC #Add_Tag_ToResource @ResourceKey = 'dev-access-api', @TagKey='Resource Group',@TagValue=N'non-prod'
--EXEC #Add_Tag_ToResource @ResourceKey = 'dev-access-api', @TagKey='Product',@TagValue=N'MPX'

--EXEC #Seed_Resource @ResourceKey='dev-mdlp',@ResourceName = 'MDLP',@ResourceTypeKey='External Service',@Description='MDLP Login'

--EXEC #ResourceDependsOn 'dev-visibility-api','dev-access-api'

----SELECT * FROM [HTResourceMapper].[TagContentType]
----SELECT * FROM [HTResourceMapper].ResourceType
----SELECT * FROM [HTResourceMapper].TagDefinition

--SELECT 
--	R.ResourceId
--	,R.ResourceUid
--	,RTYPE.TypeName 'ResourceType'
--	,R.ResourceKey
--	,R.ResourceName
--	,R.[Description]
--	,TD.TagDefinitionKey 'TagKey'
--	,RT.TagValue 'TagValue'
--	,TC.TagCode
--FROM [HTResourceMapper].[Resource] R
--LEFT OUTER JOIN [HTResourceMapper].[ResourceType] RTYPE ON R.ResourceTypeId = RTYPE.ResourceTypeId
--LEFT OUTER JOIN [HTResourceMapper].[ResourceTag] RT  ON R.ResourceId = RT.ResourceId
--LEFT OUTER JOIN [HTResourceMapper].[TagDefinition] TD ON RT.TagDefinitionId = TD.TagDefinitionId
--LEFT OUTER JOIN [HTResourceMapper].[TagContentType] TC ON TD.TagContentTypeId = TC.TagContentTypeId



--SELECT
--	R.ResourceKey 'ResourceKey' 
--	,R.ResourceName  'ResourceName'
--	,R.[Description]  'ResourceDescription'
--	,DEST.[ResourceKey] 'DependsOnResourceKey'
--	,DEST.[ResourceName] 'DependsOnResourceName'
--	,DEST.[Description] 'DependsOnResourceDescription'
--FROM
--	[HTResourceMapper].[ResourceDependency] RD
--	JOIN [HTResourceMapper].[Resource] R ON RD.ResourceId = R.ResourceId
--	JOIN [HTResourceMapper].[Resource] DEST ON RD.DependencyResourceId = DEST.ResourceId

----ROLLBACK
--COMMIT

--GO
--DROP PROC IF EXISTS #SeedTagType
--DROP PROC IF EXISTS #SeedResource
--DROP PROC IF EXISTS #SeedTagDefinition
--DROP PROC IF EXISTS #AssignTagDefToResourceType
--DROP PROC IF EXISTS #Seed_Resource
--DROP PROC IF EXISTS #AssignTagToResource
--DROP PROC IF EXISTS #ResourceDependsOn
--DROP PROC IF EXISTS #SeedResourceType
--DROP PROC IF EXISTS #Add_Tag_ToResource
--GO

