<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Libraries\ApiContracts\HT.Api.Service.Contracts\HT.Api.Service.Contracts.csproj" />
    <ProjectReference Include="..\..\..\Libraries\Configuration\HT.Microsoft.IConfiguration.Extensions\HT.Microsoft.IConfiguration.Extensions.csproj" />
    <ProjectReference Include="..\..\..\Libraries\Logging\HT.Microsoft.ILogger.Extensions\HT.Microsoft.ILogger.Extensions.csproj" />
    <ProjectReference Include="..\..\..\Libraries\SqlClient\HT.Microsoft.SqlClient.Abstractions\HT.Microsoft.SqlClient.Extensions.Abstractions.csproj" />
    <ProjectReference Include="..\..\..\Libraries\SqlClient\HT.Microsoft.SqlClient.Extensions\HT.Microsoft.SqlClient.Extensions.csproj" />
    <ProjectReference Include="..\ResourceMapper.Common.Shared\ResourceMapper.Common.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Microsoft.Extensions.Configuration.Abstractions">
      <HintPath>..\..\..\..\nuget\microsoft.extensions.configuration.abstractions\9.0.5\lib\net9.0\Microsoft.Extensions.Configuration.Abstractions.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
