---- NOTE:  Remember to enable COMMIT below
--USE [HT.Services]
--GO
--DROP PROC IF EXISTS #SeedPropertyType
--GO
--CREATE PROC #SeedPropertyType(
--    @PropertyTypeId INT
--    ,@PropertyCode VARCHAR(50)
--)
--AS
--BEGIN
--    UPDATE TOP(1)
--        [HTResourceMapper].PropertyTypes
--    SET
--        PropertyCode = @PropertyCode
--    WHERE
--        PropertyTypeId = @PropertyTypeId
--    IF @@ROWCOUNT = 0
--    BEGIN
--        INSERT INTO [HTResourceMapper].PropertyTypes (
--            PropertyTypeId,
--            PropertyCode
--        ) VALUES (
--            @PropertyTypeId
--            ,@PropertyCode
--        )
--    END
--END
--GO

--EXEC #SeedPropertyType @PropertyTypeId=0, @PropertyCode='Text'
--EXEC #SeedPropertyType @PropertyTypeId=1, @PropertyCode='Link'

--SELECT * FROM [HTResourceMapper].PropertyTypes
--ROLLBACK
----COMMIT
--GO
--DROP PROC IF EXISTS #SeedPropertyType